// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.myotis_engine

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_myotis_engine_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_myotis_engine_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "myotis_engine"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "myotis_engine"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_myotis_engine_checksum_func_available_networks_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_canonical_network_name(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_create_handle(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_drain_logs(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_engine_init(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_ens_record_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_estimate_gas_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_eth_call_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_fee_estimate_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_fee_history_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_block_by_hash_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_block_by_number_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_block_receipts_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_code_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_logs_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_storage_at_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_storage_proof_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_transaction_by_hash_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_get_transaction_receipt_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_log_index_status_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_pause_handle(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_pending_nonce_overlay(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_request_account_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_resolve_ens_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_resume_handle(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_send_raw_transaction_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_set_log_index_config(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_set_tor_enabled(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_start_handle(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_status_json(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_stop_handle(
    ): Int
    external fun uniffi_myotis_engine_checksum_func_tor_status(
    ): Int
    external fun ffi_myotis_engine_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "myotis_engine"))
        
    }
    external fun uniffi_myotis_engine_fn_func_available_networks_json(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_canonical_network_name(`nameOrAlias`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_create_handle(`network`: RustBuffer.ByValue,`dataDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_myotis_engine_fn_func_drain_logs(`max`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_engine_init(uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun uniffi_myotis_engine_fn_func_ens_record_json(`handle`: Long,`paramsJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_estimate_gas_json(`handle`: Long,`from`: RustBuffer.ByValue,`to`: RustBuffer.ByValue,`data`: RustBuffer.ByValue,`value`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_eth_call_json(`handle`: Long,`from`: RustBuffer.ByValue,`to`: RustBuffer.ByValue,`data`: RustBuffer.ByValue,`value`: RustBuffer.ByValue,`block`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_fee_estimate_json(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_fee_history_json(`handle`: Long,`blockCount`: Long,`newestBlockTag`: RustBuffer.ByValue,`percentilesJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_block_by_hash_json(`handle`: Long,`blockHashHex`: RustBuffer.ByValue,`fullTransactions`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_block_by_number_json(`handle`: Long,`blockTag`: RustBuffer.ByValue,`fullTransactions`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_block_receipts_json(`handle`: Long,`selector`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_code_json(`handle`: Long,`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_logs_json(`handle`: Long,`filterJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_storage_at_json(`handle`: Long,`address`: RustBuffer.ByValue,`position`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_storage_proof_json(`handle`: Long,`address`: RustBuffer.ByValue,`slot`: Long,`holder`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_transaction_by_hash_json(`handle`: Long,`txHashHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_get_transaction_receipt_json(`handle`: Long,`txHashHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_log_index_status_json(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_pause_handle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_myotis_engine_fn_func_pending_nonce_overlay(`handle`: Long,`addressHex`: RustBuffer.ByValue,`minedNonce`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_myotis_engine_fn_func_request_account_json(`handle`: Long,`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_resolve_ens_json(`handle`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_resume_handle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_myotis_engine_fn_func_send_raw_transaction_json(`handle`: Long,`rawTxHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_set_log_index_config(`handle`: Long,`configJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_myotis_engine_fn_func_set_tor_enabled(`on`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_myotis_engine_fn_func_start_handle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_myotis_engine_fn_func_status_json(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_myotis_engine_fn_func_stop_handle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_myotis_engine_fn_func_tor_status(uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_myotis_engine_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_myotis_engine_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_myotis_engine_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_myotis_engine_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_myotis_engine_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_myotis_engine_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_myotis_engine_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_myotis_engine_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_myotis_engine_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_myotis_engine_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_myotis_engine_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_myotis_engine_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_myotis_engine_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_myotis_engine_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_myotis_engine_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_myotis_engine_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_myotis_engine_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_myotis_engine_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_myotis_engine_checksum_func_available_networks_json() != 49639) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_canonical_network_name() != 21726) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_create_handle() != 39066) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_drain_logs() != 44503) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_engine_init() != 41182) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_ens_record_json() != 7888) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_estimate_gas_json() != 21056) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_eth_call_json() != 24325) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_fee_estimate_json() != 39989) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_fee_history_json() != 17955) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_block_by_hash_json() != 52442) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_block_by_number_json() != 42616) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_block_receipts_json() != 43710) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_code_json() != 40825) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_logs_json() != 29899) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_storage_at_json() != 24299) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_storage_proof_json() != 41815) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_transaction_by_hash_json() != 64104) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_get_transaction_receipt_json() != 56168) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_log_index_status_json() != 7764) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_pause_handle() != 51434) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_pending_nonce_overlay() != 21732) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_request_account_json() != 31953) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_resolve_ens_json() != 48380) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_resume_handle() != 4974) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_send_raw_transaction_json() != 26871) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_set_log_index_config() != 49994) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_set_tor_enabled() != 16704) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_start_handle() != 14110) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_status_json() != 5098) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_stop_handle() != 52697) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_myotis_engine_checksum_func_tor_status() != 43413) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}
        /**
         * The embedded network catalog as a JSON array of NetworkInfo objects
         * (camelCase keys, display order).
         */ fun `availableNetworksJson`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_available_networks_json(
    
        _status)
}
    )
    }
    

        /**
         * Canonical name for a name/alias, or None when unknown (the Java wrapper
         * raises `EngineException`).
         */ fun `canonicalNetworkName`(`nameOrAlias`: kotlin.String): kotlin.String? {
            return FfiConverterOptionalString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_canonical_network_name(
    
        
        FfiConverterString.lower(`nameOrAlias`),_status)
}
    )
    }
    

        /**
         * Allocate a not-yet-started handle for `network` (R1: mainnet only).
         */ fun `createHandle`(`network`: kotlin.String, `dataDir`: kotlin.String): kotlin.Long {
            return FfiConverterLong.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_create_handle(
    
        
        FfiConverterString.lower(`network`),
        FfiConverterString.lower(`dataDir`),_status)
}
    )
    }
    

        /**
         * Up to `max` buffered engine tracing lines (oldest first, newline-joined;
         * empty when idle) — the drainable-ring end of the observability seam.
         */ fun `drainLogs`(`max`: kotlin.Int): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_drain_logs(
    
        
        FfiConverterInt.lower(`max`),_status)
}
    )
    }
    

        /**
         * ABI handshake: installs the ring-buffer tracing subscriber (idempotent) and
         * returns the compiled-in [`crate::ABI_VERSION`]. UniFFI's checksum validation
         * already guarantees signature compatibility; this coarse version remains for
         * the wrapper's log line and as a shared constant with the iOS C ABI.
         */ fun `engineInit`(): kotlin.Int {
            return FfiConverterInt.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_engine_init(
    
        _status)
}
    )
    }
    

        /**
         * One generic ENS record dispatch; the method and its args travel in `params_json`.
         */ fun `ensRecordJson`(`handle`: kotlin.Long, `paramsJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_ens_record_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`paramsJson`),_status)
}
    )
    }
    

        /**
         * Verified `eth_estimateGas` over the revm executor (verified head; no block arg).
         */ fun `estimateGasJson`(`handle`: kotlin.Long, `from`: kotlin.String, `to`: kotlin.String, `data`: kotlin.String, `value`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_estimate_gas_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`from`),
        FfiConverterString.lower(`to`),
        FfiConverterString.lower(`data`),
        FfiConverterString.lower(`value`),_status)
}
    )
    }
    

        /**
         * Verified `eth_call` over the revm executor. `from` empty ⇒ anonymous call;
         * `value` is wei as a decimal string; `block` is the RPC block tag.
         */ fun `ethCallJson`(`handle`: kotlin.Long, `from`: kotlin.String, `to`: kotlin.String, `data`: kotlin.String, `value`: kotlin.String, `block`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_eth_call_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`from`),
        FfiConverterString.lower(`to`),
        FfiConverterString.lower(`data`),
        FfiConverterString.lower(`value`),
        FfiConverterString.lower(`block`),_status)
}
    )
    }
    

        /**
         * Verified fee suggestion (`eth_gasPrice` + `eth_maxPriorityFeePerGas`).
         */ fun `feeEstimateJson`(`handle`: kotlin.Long): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_fee_estimate_json(
    
        
        FfiConverterLong.lower(`handle`),_status)
}
    )
    }
    

        /**
         * Verified `eth_feeHistory`. `percentiles_json` is a JSON array of reward
         * percentiles, or empty to omit the reward matrix.
         */ fun `feeHistoryJson`(`handle`: kotlin.Long, `blockCount`: kotlin.Long, `newestBlockTag`: kotlin.String, `percentilesJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_fee_history_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterLong.lower(`blockCount`),
        FfiConverterString.lower(`newestBlockTag`),
        FfiConverterString.lower(`percentilesJson`),_status)
}
    )
    }
    

        /**
         * Verified `eth_getBlockByHash` (hashes this engine has already verified).
         */ fun `getBlockByHashJson`(`handle`: kotlin.Long, `blockHashHex`: kotlin.String, `fullTransactions`: kotlin.Boolean): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_block_by_hash_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`blockHashHex`),
        FfiConverterBoolean.lower(`fullTransactions`),_status)
}
    )
    }
    

        /**
         * Verified `eth_getBlockByNumber` (`full_transactions` selects decoded tx
         * objects over hashes). Returns the block JSON, the literal `"null"`, or
         * `{"error": ...}`.
         */ fun `getBlockByNumberJson`(`handle`: kotlin.Long, `blockTag`: kotlin.String, `fullTransactions`: kotlin.Boolean): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_block_by_number_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`blockTag`),
        FfiConverterBoolean.lower(`fullTransactions`),_status)
}
    )
    }
    

        /**
         * Verified `eth_getBlockReceipts` for a tag / 0x-number / 0x-32-byte-hash selector.
         */ fun `getBlockReceiptsJson`(`handle`: kotlin.Long, `selector`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_block_receipts_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`selector`),_status)
}
    )
    }
    

        /**
         * Verified contract-code query (`eth_getCode`).
         */ fun `getCodeJson`(`handle`: kotlin.Long, `address`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_code_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`address`),_status)
}
    )
    }
    

        /**
         * eth_getLogs over the opt-in watch-list index: the log array on success,
         * `{"error": ...}` otherwise — including for any range outside indexed
         * coverage (never an empty array for unindexed blocks).
         */ fun `getLogsJson`(`handle`: kotlin.Long, `filterJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_logs_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`filterJson`),_status)
}
    )
    }
    

        /**
         * Verified RAW-32-byte-position storage query (`eth_getStorageAt`).
         */ fun `getStorageAtJson`(`handle`: kotlin.Long, `address`: kotlin.String, `position`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_storage_at_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`address`),
        FfiConverterString.lower(`position`),_status)
}
    )
    }
    

        /**
         * Verified storage-slot query (`StorageProofResult` shape). A non-None `holder`
         * selects the ERC-20 mapping key `keccak256(pad32(holder) ‖ uint256(slot))`.
         */ fun `getStorageProofJson`(`handle`: kotlin.Long, `address`: kotlin.String, `slot`: kotlin.Long, `holder`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_storage_proof_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`address`),
        FfiConverterLong.lower(`slot`),
        FfiConverterOptionalString.lower(`holder`),_status)
}
    )
    }
    

        /**
         * Verified `eth_getTransactionByHash`. Returns the tx JSON, the literal
         * `"null"` (verified "not seen"), or `{"error": ...}`.
         */ fun `getTransactionByHashJson`(`handle`: kotlin.Long, `txHashHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_transaction_by_hash_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`txHashHex`),_status)
}
    )
    }
    

        /**
         * Verified `eth_getTransactionReceipt`. Returns the receipt JSON, the literal
         * `"null"` (verified "not seen"), or `{"error": ...}`.
         */ fun `getTransactionReceiptJson`(`handle`: kotlin.Long, `txHashHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_get_transaction_receipt_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`txHashHex`),_status)
}
    )
    }
    

        /**
         * Log-index status JSON: enabled flag, log count, backfill cursor, and per
         * watch entry its covered span.
         */ fun `logIndexStatusJson`(`handle`: kotlin.Long): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_log_index_status_json(
    
        
        FfiConverterLong.lower(`handle`),_status)
}
    )
    }
    

        /**
         * Idle-sleep a RUNNING handle. True ONLY on an actual RUNNING→PAUSED transition.
         */ fun `pauseHandle`(`handle`: kotlin.Long): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_pause_handle(
    
        
        FfiConverterLong.lower(`handle`),_status)
}
    )
    }
    

        /**
         * The "pending" nonce overlay; negative only for malformed input / a missing
         * handle (the adapter then serves the plain mined nonce).
         */ fun `pendingNonceOverlay`(`handle`: kotlin.Long, `addressHex`: kotlin.String, `minedNonce`: kotlin.Long): kotlin.Long {
            return FfiConverterLong.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_pending_nonce_overlay(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`addressHex`),
        FfiConverterLong.lower(`minedNonce`),_status)
}
    )
    }
    

        /**
         * Verified account query (`AccountProofResult` shape). `address` is 0x-hex.
         */ fun `requestAccountJson`(`handle`: kotlin.Long, `address`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_request_account_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`address`),_status)
}
    )
    }
    

        /**
         * Verified ENS forward resolution (name → address record).
         */ fun `resolveEnsJson`(`handle`: kotlin.Long, `name`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_resolve_ens_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`name`),_status)
}
    )
    }
    

        /**
         * Rebuild networking for a PAUSED handle (warm start). True ONLY on an actual
         * PAUSED→RUNNING transition.
         */ fun `resumeHandle`(`handle`: kotlin.Long): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_resume_handle(
    
        
        FfiConverterLong.lower(`handle`),_status)
}
    )
    }
    

        /**
         * Gossip a signed raw transaction; `{"txHash":"0x…"}` or `{"error": ...}`.
         */ fun `sendRawTransactionJson`(`handle`: kotlin.Long, `rawTxHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_send_raw_transaction_json(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`rawTxHex`),_status)
}
    )
    }
    

        /**
         * Install the log-index watch-list config (JSON; see host docs). False on
         * malformed config, duplicate addresses, or an unavailable reader.
         */ fun `setLogIndexConfig`(`handle`: kotlin.Long, `configJson`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_set_log_index_config(
    
        
        FfiConverterLong.lower(`handle`),
        FfiConverterString.lower(`configJson`),_status)
}
    )
    }
    

        /**
         * Toggle Tor verified-read routing (docs/privacy-and-tor.md). Returns true iff
         * this build supports Tor (`--features tor`); a Tor-less build returns false and
         * no-ops. Process-global, not per-handle.
         */ fun `setTorEnabled`(`on`: kotlin.Boolean): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_set_tor_enabled(
    
        
        FfiConverterBoolean.lower(`on`),_status)
}
    )
    }
    

        /**
         * Start the sync loop for a created handle. True on success.
         */ fun `startHandle`(`handle`: kotlin.Long): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_start_handle(
    
        
        FfiConverterLong.lower(`handle`),_status)
}
    )
    }
    

        /**
         * One handle's status as a JSON object, or `"{}"` for an unknown handle.
         */ fun `statusJson`(`handle`: kotlin.Long): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_status_json(
    
        
        FfiConverterLong.lower(`handle`),_status)
}
    )
    }
    

        /**
         * Remove and shut down a handle's sync loop. No-op for an unknown id.
         */ fun `stopHandle`(`handle`: kotlin.Long)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_stop_handle(
    
        
        FfiConverterLong.lower(`handle`),_status)
}
    
    

        /**
         * Tor status bitmask for the host Status view: bit0 compiled-in, bit1 enabled,
         * bit2 bootstrapped. `0` = this build has no Tor support.
         */ fun `torStatus`(): kotlin.Int {
            return FfiConverterInt.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_myotis_engine_fn_func_tor_status(
    
        _status)
}
    )
    }
    


