java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation(libs.tuweni.bytes)
    implementation(libs.tuweni.rlp)
    implementation(libs.tuweni.crypto)
    implementation(libs.tuweni.units)
    implementation(libs.bouncycastle)
    implementation(libs.slf4j.api)

    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.logback.classic)
}

// Build-time identity GENERATED from the Gradle release version, so the release
// sweep has no literal to forget: the Java engine's devp2p Hello client id
// (:networking's HelloMessage) and its libp2p Identify agent (:consensus's
// BeaconP2PService) both read it. The Rust engine derives the same strings from
// CARGO_PKG_VERSION, and they must agree — dedicated myotis-serving nodes admit
// peers by matching "myotis" in the Hello id. The Hello id used to be a
// hand-edited literal, the one version pin no check covered: a sweep that
// missed it shipped a Java engine advertising the previous release with green
// CI. It lived in :networking until the Identify agent needed it as well; :core
// is the module both depend on. Same shape as :ui's generateUiBuildInfo; plain
// String inputs, so it is configuration-cache compatible and regenerates
// exactly when the version changes.
val releaseVersion = project.version.toString().substringBefore('-')
val generateCoreBuildInfo by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/buildInfo/java")
    val version = releaseVersion
    inputs.property("releaseVersion", version)
    outputs.dir(outDir)
    doLast {
        // Escaped because this lands inside a Java string LITERAL. Unreachable
        // today (the version is a numeric MAJOR.MINOR.PATCH), but a stray " or \
        // would emit a file that doesn't compile.
        val literal = version.replace("\\", "\\\\").replace("\"", "\\\"")
        val f = outDir.get().file("com/jaeckel/ethp2p/core/BuildInfo.java").asFile
        f.parentFile.mkdirs()
        f.writeText(
            """
            // GENERATED by :core's generateCoreBuildInfo task — do not edit.
            package com.jaeckel.ethp2p.core;

            /** Build-time constants derived from the Gradle project version. */
            public final class BuildInfo {
                /** The release version: the Gradle project version without its {@code -SNAPSHOT} suffix. */
                public static final String RELEASE_VERSION = "$literal";

                /** The devp2p Hello client id: {@code myotis/<release version>}. */
                public static final String CLIENT_ID = "myotis/" + RELEASE_VERSION;

                private BuildInfo() {}
            }
            """.trimIndent() + "\n",
        )
    }
}
sourceSets.main { java.srcDir(generateCoreBuildInfo) }

tasks.test {
    // BuildInfoTest derives the release version from the raw project version
    // on its own and compares it with the generated constant.
    systemProperty("myotis.projectVersion", project.version.toString())
}
