#!/usr/bin/env bash
# Sudo-side installer for roost, the dedicated light-client server
# (docs/lc-server-design.md). Same shape as install-sepolia-node.sh.
#
# Build first, as your normal user:
#   cd <repo> && cargo build --release --manifest-path rust/roost/Cargo.toml
# Then:
#   sudo bash rust/roost/deploy/install-roost.sh
#
# Idempotent: safe to re-run to upgrade the binary. It never touches
# /data/roost/sepolia.key once that exists — see the note below.
set -euo pipefail

# Override to install a binary built elsewhere.
REPO="${REPO:-$(cd "$(dirname "$0")/../../.." && pwd)}"
ROOST_BIN="${ROOST_BIN:-$REPO/rust/roost/target/release/roost}"
PORT=9105

[ -x "$ROOST_BIN" ] || { echo "roost not built yet: $ROOST_BIN missing"; exit 1; }

# --- host setup ---
id roost >/dev/null 2>&1 || useradd --system --home /data/roost --shell /usr/sbin/nologin roost
mkdir -p /data/roost
chown -R roost:roost /data/roost
chmod 750 /data/roost

# Firewall. NOTE: also forward 9105 tcp on the router — and 9105 udp as well
# once discv5 is published, which it is not yet.
if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
  ufw allow ${PORT}/tcp
fi

# --- install ---
install -o root -g root -m 0755 "$ROOST_BIN" /usr/local/bin/roost
install -o root -g root -m 0644 "$(dirname "$0")/roost-sepolia.service" \
  /etc/systemd/system/roost-sepolia.service

systemctl daemon-reload
systemctl enable roost-sepolia.service

cat <<'NOTE'

Installed. Not started — `systemctl start roost-sepolia` when you want it.

Requires Nimbus's REST API, which the current unit already enables:
  --rest (binds 127.0.0.1:5052) and --light-client-data-serve=true

THE IDENTITY FILE IS THE ONE THING WORTH BACKING UP.

  /data/roost/sepolia.key

roost creates it 0600 on first start. It is the libp2p host key AND the discv5
key — wallets derive the peer id they dial from it. Losing or replacing it
re-mints the node id, which un-learns this server from every wallet that had
cached it and burns their strikes-to-eviction on a node that is actually fine.
This installer never overwrites it.

  /data/roost/sepolia.db     the light-client archive. Periods below Nimbus's
                             floor cannot be regenerated by anything we run, so
                             back it up once it holds more than the live window.
                             Today it is refetchable in seconds.
  /data/roost/sepolia.enrseq the ENR sequence number. BACK IT UP WITH THE KEY —
                             restoring one without the other is worse than
                             restoring neither. It restarts at 1 when missing,
                             so the DHT ignores every record until the count
                             climbs back past the last published value: the node
                             looks healthy and is undiscoverable.

Check it with:
  systemctl status roost-sepolia
  journalctl -u roost-sepolia -f
  sudo -u roost /usr/local/bin/roost probe --rest http://127.0.0.1:5052

RUN `roost enr` AS THE SERVICE USER, NOT ROOT. It WRITES: it consumes a sequence
number on every run, and creates the identity key if absent. As root it would
leave both root-owned and the service unable to read them.

  sudo -u roost /usr/local/bin/roost enr \\
      --archive /data/roost/sepolia.db --advertise <public-ip>

NOTE
