#!/usr/bin/env bash
# Install one roost instance:  sudo bash deploy/install-roost-instance.sh mainnet
#
# roost is one chain per process. Each instance gets its own archive, identity,
# port and upstream; the template unit reads the per-chain bits from
# /etc/myotis/roost-<chain>.env because ports cannot be derived from the name.
#
# Idempotent, and it NEVER touches an existing identity key — replacing that
# re-mints the peer id, which un-learns the server from every wallet that had
# cached it.
set -euo pipefail

STAGE="$(cd "$(dirname "$0")" && pwd)"
chain="${1:-}"
case "$chain" in
  sepolia) PORT=9105; UPSTREAM_REST=5052 ;;
  gnosis)  PORT=9108; UPSTREAM_REST=5053 ;;
  mainnet) PORT=9109; UPSTREAM_REST=5054 ;;
  *) echo "usage: $0 <sepolia|gnosis|mainnet>"; exit 1 ;;
esac

ROOST_BIN="${ROOST_BIN:-}"
if [ -z "$ROOST_BIN" ]; then
  INVOKING_HOME="$(getent passwd "${SUDO_USER:-$(id -un)}" | cut -d: -f6)"
  ROOST_BIN="$INVOKING_HOME/myotis/rust/roost/target/release/roost"
fi
[ -x "$ROOST_BIN" ] || { echo "roost not built at $ROOST_BIN"; exit 1; }

# The upstream must be answering before roost is pointed at it: roost's first
# call is genesis_validators_root, and under Restart=on-failure a dead upstream
# is a restart loop rather than a clear error.
if ! curl -sf -m 5 "http://127.0.0.1:$UPSTREAM_REST/eth/v1/node/version" >/dev/null; then
  echo "!!! no beacon REST on 127.0.0.1:$UPSTREAM_REST — start nimbus-$chain first"
  exit 1
fi

id roost >/dev/null 2>&1 || useradd --system --home /data/roost --shell /usr/sbin/nologin roost
mkdir -p /data/roost /etc/myotis
chown -R roost:roost /data/roost
chmod 750 /data/roost

cat > "/etc/myotis/roost-$chain.env" <<ENV
# Generated by install-roost-instance.sh — per-chain settings for roost@$chain
ROOST_PORT=$PORT
ROOST_UPSTREAM_REST=$UPSTREAM_REST
ENV
chmod 644 "/etc/myotis/roost-$chain.env"

install -o root -g root -m 0644 "$STAGE/roost@.service" /etc/systemd/system/roost@.service
install -o root -g root -m 0755 "$ROOST_BIN" /usr/local/bin/roost

if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
  ufw allow "$PORT/tcp"
fi

systemctl daemon-reload
systemctl enable "roost@$chain"

echo
echo "Installed roost@$chain (tcp $PORT, upstream 127.0.0.1:$UPSTREAM_REST). Start it:"
echo "  sudo systemctl start roost@$chain"
echo "  journalctl -u roost@$chain -f"
echo
echo "The peer id in the startup banner is what gets PINNED into NetworkConfig."
echo "It comes from /data/roost/$chain.key — back that up; replacing it re-mints"
echo "the identity and un-learns this server from every wallet that cached it."
echo "Forward $PORT/tcp on the router, or wallets cannot reach it."
