#!/usr/bin/env bash
# Install one roost instance:  sudo bash deploy/install-roost-instance.sh mainnet
#
# roost is one chain per process. Each instance gets its own archive, identity,
# port and upstream; the template unit reads the per-chain bits from
# /etc/myotis/roost-<chain>.env because ports cannot be derived from the name.
#
# Idempotent, and it NEVER touches an existing identity key — replacing that
# re-mints the peer id, which un-learns the server from every wallet that had
# cached it.
set -euo pipefail

STAGE="$(cd "$(dirname "$0")" && pwd)"
chain="${1:-}"
case "$chain" in
  sepolia) PORT=9105; UPSTREAM_REST=5052 ;;
  gnosis)  PORT=9108; UPSTREAM_REST=5053 ;;
  mainnet) PORT=9109; UPSTREAM_REST=5054 ;;
  *) echo "usage: $0 <sepolia|gnosis|mainnet>"; exit 1 ;;
esac

ROOST_BIN="${ROOST_BIN:-}"
if [ -z "$ROOST_BIN" ]; then
  INVOKING_HOME="$(getent passwd "${SUDO_USER:-$(id -un)}" | cut -d: -f6)"
  ROOST_BIN="$INVOKING_HOME/myotis/rust/roost/target/release/roost"
fi
[ -x "$ROOST_BIN" ] || { echo "roost not built at $ROOST_BIN"; exit 1; }

# The upstream must be answering before roost is pointed at it: roost's first
# call is genesis_validators_root, and under Restart=on-failure a dead upstream
# is a restart loop rather than a clear error.
if ! curl -sf -m 5 "http://127.0.0.1:$UPSTREAM_REST/eth/v1/node/version" >/dev/null; then
  echo "!!! no beacon REST on 127.0.0.1:$UPSTREAM_REST — start nimbus-$chain first"
  exit 1
fi

id roost >/dev/null 2>&1 || useradd --system --home /data/roost --shell /usr/sbin/nologin roost
mkdir -p /data/roost /etc/myotis
chown -R roost:roost /data/roost
chmod 750 /data/roost

# Written ONCE: the env file carries operator decisions now (clearing
# ROOST_EXTRA_ARGS is how publication gets enabled), and a re-run after an
# upgrade must not silently revert a published instance to --no-publish.
ENVFILE="/etc/myotis/roost-$chain.env"
if [ ! -f "$ENVFILE" ]; then
  cat > "$ENVFILE" <<ENV
# Generated by install-roost-instance.sh — per-chain settings for roost@$chain
ROOST_PORT=$PORT
ROOST_UPSTREAM_REST=$UPSTREAM_REST
# Deployment step 1 (#335): join the discv5 DHT, publish nothing. Once
# $PORT/udp is forwarded on the router AND verified reachable from outside
# (see README §Ports — the "discv5 health" line alone does not prove inbound),
# set this empty and restart to let the ENR publish.
ROOST_EXTRA_ARGS=--no-publish
ENV
  chmod 644 "$ENVFILE"
else
  echo "keeping existing $ENVFILE (operator-owned; not overwritten)"
  # A pre-#335 env has no ROOST_EXTRA_ARGS, and systemd expands the unset
  # variable to nothing — which would silently turn publication ON for an
  # upgraded instance that never went through deployment step 1. Upgrades get
  # the same join-only default as fresh installs; enabling publication stays
  # an explicit operator edit.
  if ! grep -q '^ROOST_EXTRA_ARGS=' "$ENVFILE"; then
    # Leading \n: if the operator's editor left the last line without a
    # trailing newline, a bare append would glue the comment onto it — and
    # systemd's EnvironmentFile does NOT strip inline comments, so that line's
    # value would silently grow a "# Added…" suffix. A blank line is harmless.
    printf '\n# Added on upgrade (#335): see the fresh-install comment — clear to publish.\nROOST_EXTRA_ARGS=--no-publish\n' >> "$ENVFILE"
    echo "added ROOST_EXTRA_ARGS=--no-publish to $ENVFILE (deployment step 1; clear it to publish)"
  fi
  # The kept file's port wins over this run's argument — the ufw rules below
  # must match what roost will actually bind, not what the re-run happened to
  # be invoked for.
  KEPT_PORT="$(sed -n 's/^ROOST_PORT=//p' "$ENVFILE" | tail -n1)"
  if [ -n "$KEPT_PORT" ] && [ "$KEPT_PORT" != "$PORT" ]; then
    echo "NOTE: existing $ENVFILE sets ROOST_PORT=$KEPT_PORT (not $PORT); using $KEPT_PORT"
    PORT="$KEPT_PORT"
  fi
fi

install -o root -g root -m 0644 "$STAGE/roost@.service" /etc/systemd/system/roost@.service
install -o root -g root -m 0755 "$ROOST_BIN" /usr/local/bin/roost

if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
  ufw allow "$PORT/tcp"
  # discv5 binds the same port number over UDP (#335).
  ufw allow "$PORT/udp"
fi

systemctl daemon-reload
systemctl enable "roost@$chain"

echo
echo "Installed roost@$chain (tcp $PORT, upstream 127.0.0.1:$UPSTREAM_REST). Start it:"
echo "  sudo systemctl start roost@$chain"
echo "  journalctl -u roost@$chain -f"
echo
echo "The peer id in the startup banner is what gets PINNED into NetworkConfig."
echo "It comes from /data/roost/$chain.key — back that up TOGETHER WITH"
echo "/data/roost/$chain.enrseq; an identity restored without its sequence file"
echo "re-issues ENR sequence numbers the DHT has already seen and the node goes"
echo "silently undiscoverable."
echo "Forward $PORT/tcp AND $PORT/udp on the router: tcp is how wallets reach"
echo "it, udp is how discv5 peers prove its endpoint so they will hand out its"
echo "record. Installs default to --no-publish (join-only). The 'discv5 health'"
echo "log line only proves the node JOINED (outbound); verify INBOUND udp from"
echo "outside the LAN (README §Ports) before clearing ROOST_EXTRA_ARGS in"
echo "/etc/myotis/roost-$chain.env and restarting to publish."
