#!/usr/bin/env python3
"""Generate the Android launcher / status-bar icons from assets/myotis_logo.svg.

Usage: python3 scripts/gen_android_icons.py [--preview DIR]

Writes android-app/src/main/res/{drawable/ic_launcher_foreground.xml,
drawable/ic_stat_myotis.xml, values/ic_launcher_background.xml,
mipmap-anydpi-v26/ic_launcher*.xml}. Needs only the stdlib; --preview DIR also
renders a preview sheet there (needs cairosvg + Pillow: pip install cairosvg pillow).

Reads the bat's four fill paths, normalises their path data (one line, two
decimals, no tabs — Android's PathParser treats only ' ' and ',' as separators),
and writes VectorDrawables whose <group> places the bat on a square canvas:
Android applies scale first, then translate (pivot 0), so p' = s*p + t.
"""
import re, sys, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREVIEW = sys.argv[sys.argv.index('--preview') + 1] if '--preview' in sys.argv else None
svg = open(os.path.join(ROOT, 'assets/myotis_logo.svg')).read()
paths = re.findall(r"\sd=\"\s*([^\"]+)\"", svg)
tok = re.compile(r'[MCZz]|-?\d*\.?\d+(?:e-?\d+)?')

def normalise(d):
    toks = tok.findall(d); out = []; i = 0
    while i < len(toks):
        t = toks[i]
        if t == 'M':
            out.append('M%s,%s' % (f(toks[i+1]), f(toks[i+2]))); i += 3
        elif t == 'C':
            out.append('C' + ' '.join('%s,%s' % (f(toks[i+k]), f(toks[i+k+1])) for k in (1, 3, 5))); i += 7
        elif t in 'Zz':
            out.append('Z'); i += 1
        else:
            raise SystemExit('unexpected token ' + t)
    return ' '.join(out)

def f(s):
    v = round(float(s), 2)
    return ('%.2f' % v).rstrip('0').rstrip('.')

norm = [normalise(d) for d in paths]

def bounds(ds):
    """Bounding box of the paths' flattened curves (16 samples per cubic)."""
    xs, ys = [], []
    for d in ds:
        toks = tok.findall(d); i = 0; cur = None; start = None
        while i < len(toks):
            t = toks[i]
            if t == 'M':
                cur = start = (float(toks[i+1]), float(toks[i+2])); xs.append(cur[0]); ys.append(cur[1]); i += 3
            elif t == 'C':
                p0 = cur; p1, p2, p3 = [(float(toks[i+k]), float(toks[i+k+1])) for k in (1, 3, 5)]
                for k in range(1, 17):
                    u = k / 16; a, b, c, e = (1-u)**3, 3*(1-u)**2*u, 3*(1-u)*u*u, u**3
                    xs.append(a*p0[0] + b*p1[0] + c*p2[0] + e*p3[0]); ys.append(a*p0[1] + b*p1[1] + c*p2[1] + e*p3[1])
                cur = p3; i += 7
            else:
                cur = start; i += 1
    return min(xs), max(xs), min(ys), max(ys)

X0, X1, Y0, Y1 = bounds(paths)   # the bat: x 302.86..723.43, y 147.56..410.89 in the SVG's 1024x544
CX, CY = (X0 + X1) / 2, (Y0 + Y1) / 2

def vector(size, scale, fill, comment):
    tx, ty = size / 2 - CX * scale, size / 2 - CY * scale
    body = '\n'.join(
        '        <path\n            android:fillColor="%s"\n            android:pathData="%s" />' % (fill, d)
        for d in norm)
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!--\n%s\n-->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="%ddp"\n    android:height="%ddp"\n'
            '    android:viewportWidth="%d"\n    android:viewportHeight="%d">\n'
            '    <group\n        android:scaleX="%s"\n        android:scaleY="%s"\n'
            '        android:translateX="%s"\n        android:translateY="%s">\n%s\n    </group>\n</vector>\n'
            % (comment, size, size, size, size, scale, scale, f(tx), f(ty), body)), (tx, ty)

res = os.path.join(ROOT, 'android-app/src/main/res')
os.makedirs(os.path.join(res, 'drawable'), exist_ok=True)
os.makedirs(os.path.join(res, 'mipmap-anydpi-v26'), exist_ok=True)

FG_SCALE = 0.14     # 420.57 source units -> 58.9dp: the wing tips sit on the 66dp safe-zone circle
STAT_SCALE = 0.052  # -> 21.9dp of the 24dp status-bar icon
fg, (fgtx, fgty) = vector(108, FG_SCALE, '#FFFFFFFF',
    '  The bat from assets/myotis_logo.svg (same four fill paths, path data normalised to one\n'
    '  line) as the adaptive launcher icon\'s foreground layer. Generated by\n'
    '  scripts/gen_android_icons.py — edit the SVG and re-run, do not hand-edit the paths.\n'
    '  The 108dp canvas is what launchers mask: the inner 72dp is visible, and the bat\'s wing\n'
    '  tips are scaled to sit on the 66dp safe-zone circle so no mask shape clips them.')
stat, (sttx, stty) = vector(24, STAT_SCALE, '#FFFFFFFF',
    '  The same bat as a 24dp status-bar icon for the foreground-service notification (white on\n'
    '  transparent, as small icons must be — the system tints it). Generated by\n'
    '  scripts/gen_android_icons.py from assets/myotis_logo.svg; do not hand-edit the paths.')
open(os.path.join(res, 'drawable/ic_launcher_foreground.xml'), 'w').write(fg)
open(os.path.join(res, 'drawable/ic_stat_myotis.xml'), 'w').write(stat)
open(os.path.join(res, 'values/ic_launcher_background.xml'), 'w').write(
    '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
    '    <!-- Adaptive launcher icon background: the brand dark from assets/social-preview.svg,\n'
    '         behind the white bat (the dark-scheme logo, assets/myotis_logo_dark.svg). -->\n'
    '    <color name="ic_launcher_background">#1A1A24</color>\n</resources>\n')
adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
    '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
    '    <background android:drawable="@color/ic_launcher_background" />\n'
    '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
    '    <!-- Android 13+ themed icons use the foreground\'s alpha, tinted by the launcher. -->\n'
    '    <monochrome android:drawable="@drawable/ic_launcher_foreground" />\n'
    '</adaptive-icon>\n')
for n in ('ic_launcher.xml', 'ic_launcher_round.xml'):
    open(os.path.join(res, 'mipmap-anydpi-v26', n), 'w').write(adaptive)

# ---- preview sheet (opt-in: --preview DIR; cairosvg + Pillow) ----
print('foreground translate', f(fgtx), f(fgty), '| stat translate', f(sttx), f(stty))
if PREVIEW is None:
    sys.exit(0)
import cairosvg
from PIL import Image, ImageDraw
OUT = PREVIEW
def render(size, scale, tx, ty, bg, fill, px):
    g = ''.join('<path fill="%s" d="%s"/>' % (fill, d) for d in norm)
    s = ('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">'
         '%s<g transform="translate(%s,%s) scale(%s)">%s</g></svg>'
         % (px, px, size, size, ('<rect width="%d" height="%d" fill="%s"/>' % (size, size, bg)) if bg else '', tx, ty, scale, g))
    return Image.open(__import__('io').BytesIO(cairosvg.svg2png(bytestring=s.encode()))).convert('RGBA')

full = render(108, FG_SCALE, fgtx, fgty, '#1A1A24', '#FFFFFF', 432)
# visible 72dp window + 66dp safe-zone circle, drawn on a copy for inspection
insp = full.copy(); d = ImageDraw.Draw(insp)
d.rectangle([72, 72, 360, 360], outline='#FF5252', width=2)   # 72dp visible window
d.ellipse([84, 84, 348, 348], outline='#69F0AE', width=2)     # 66dp safe zone
def masked(shape):
    win = full.crop((72, 72, 360, 360)); m = Image.new('L', win.size, 0); md = ImageDraw.Draw(m)
    if shape == 'circle': md.ellipse([0, 0, 287, 287], fill=255)
    else: md.rounded_rectangle([0, 0, 287, 287], radius=72, fill=255)
    out = Image.new('RGBA', win.size, (0, 0, 0, 0)); out.paste(win, (0, 0), m); return out
stat_img = render(24, STAT_SCALE, sttx, stty, None, '#FFFFFF', 96)
sheet = Image.new('RGBA', (432 + 288 + 288 + 96 + 5 * 24, 432 + 48), '#607D8B')
sheet.paste(insp, (24, 24)); sheet.paste(masked('circle'), (480, 96), masked('circle'))
sheet.paste(masked('squircle'), (792, 96), masked('squircle'))
bar = Image.new('RGBA', (96, 96), '#000000'); bar.paste(stat_img, (0, 0), stat_img); sheet.paste(bar, (1104, 96))
sheet.save(os.path.join(OUT, 'preview.png'))
print('wrote', os.path.join(OUT, 'preview.png'))
