#!/usr/bin/env python3
"""Golden vector for the RelayAdapt7702 shield builder (#509).

Builds the synthetic "shield ETH" transaction that
``rust/myotis-evm/src/fixture/relay_adapt_7702.rs`` builds, with an independent
implementation: eth-account for the EIP-712 execute signature and the EIP-7702
authorization, eth-abi for the calldata. Both follow the RAILGUN wallet SDK
(``@railgun-community/wallet`` 11.2 ``tx-shield-base-token-7702.js``,
``@railgun-community/engine`` 9.8 ``relay-adapt-7702-signature.js``).

The keys are throwaway constants (0x11..11 for the ephemeral account, 0x22..22
for the sender), so the vector is reproducible. The Rust test compares its
build byte for byte against the output, which is committed as
``rust/myotis-evm/src/fixture/relay_adapt_7702_golden.json``:

    pip install 'eth-account>=0.13' eth-abi
    ./scripts/relay_adapt_7702_golden.py > rust/myotis-evm/src/fixture/relay_adapt_7702_golden.json

No network access: nothing here reads chain state.
"""
import json

from eth_abi import encode
from eth_account import Account
from eth_account.messages import encode_typed_data
from eth_utils import keccak, to_checksum_address

CHAIN_ID = 1
# The RelayAdapt7702 #509's failing transactions delegated to.
DELEGATE = "0x05ae73c5925d843864ae6f261f3175de2ebcd963"
WETH = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
VALUE = 10**16
EPHEMERAL_KEY = bytes([0x11]) * 32
SENDER_KEY = bytes([0x22]) * 32

TRANSACTION = (
    "(((uint256,uint256),(uint256[2],uint256[2]),(uint256,uint256)),bytes32,bytes32[],bytes32[],"
    "(uint16,uint72,uint8,uint64,address,bytes32,(bytes32[4],bytes32,bytes32,bytes,bytes)[]),"
    "(bytes32,(uint8,address,uint256),uint120))[]"
)
ACTION_DATA = "(bool,uint256,(address,bytes,uint256)[])"
SHIELD_REQUEST = "((bytes32,(uint8,address,uint256),uint120),(bytes32[3],bytes32))[]"


def selector(signature: str) -> bytes:
    return keccak(signature.encode())[:4]


def main() -> None:
    ephemeral = Account.from_key(EPHEMERAL_KEY)
    sender = Account.from_key(SENDER_KEY)
    npk = bytes([0x0A]) * 32
    bundle = [bytes([0xB1]) * 32, bytes([0xB2]) * 32, bytes([0xB3]) * 32]
    shield_key = bytes([0x5C]) * 32
    request = ((npk, (0, WETH, 0), VALUE), (bundle, shield_key))
    calls = [
        (ephemeral.address, selector("wrapBase(uint256)") + encode(["uint256"], [VALUE]), 0),
        (ephemeral.address, selector(f"shield({SHIELD_REQUEST})") + encode([SHIELD_REQUEST], [[request]]), 0),
    ]
    action_data = (True, 0, calls)
    execute_nonce = 0
    payload_hash = keccak(encode([TRANSACTION, ACTION_DATA, "uint256"], [[], action_data, execute_nonce]))
    typed = {
        "types": {
            "EIP712Domain": [
                {"name": "name", "type": "string"},
                {"name": "version", "type": "string"},
                {"name": "chainId", "type": "uint256"},
                {"name": "verifyingContract", "type": "address"},
            ],
            "Execute": [{"name": "payloadHash", "type": "bytes32"}],
        },
        "primaryType": "Execute",
        "domain": {"name": "RelayAdapt7702", "version": "1", "chainId": CHAIN_ID, "verifyingContract": ephemeral.address},
        "message": {"payloadHash": payload_hash},
    }
    signature = Account.sign_message(encode_typed_data(full_message=typed), EPHEMERAL_KEY).signature
    data = selector(f"execute({TRANSACTION},{ACTION_DATA},uint256,bytes)") + encode(
        [TRANSACTION, ACTION_DATA, "uint256", "bytes"], [[], action_data, execute_nonce, bytes(signature)]
    )
    auth = Account.sign_authorization(
        {"chainId": CHAIN_ID, "address": to_checksum_address(DELEGATE), "nonce": 0}, EPHEMERAL_KEY
    )
    print(json.dumps({
        "_note": "Generated by scripts/relay_adapt_7702_golden.py (eth-account, eth-abi) from throwaway keys.",
        "ephemeral": ephemeral.address.lower(),
        "payloadHash": "0x" + payload_hash.hex(),
        "request": {
            "from": sender.address.lower(),
            "to": ephemeral.address.lower(),
            "value": hex(VALUE),
            "data": "0x" + data.hex(),
            "type": "0x4",
            "authorizationList": [{
                "chainId": hex(auth.chain_id),
                "address": DELEGATE,
                "nonce": hex(auth.nonce),
                "yParity": hex(auth.y_parity),
                "r": hex(auth.r),
                "s": hex(auth.s),
            }],
        },
    }, indent=2))


if __name__ == "__main__":
    main()
